version: "3"

# Named volumes
volumes:
  my-db:

services:
  postgres:
    container_name: expanse-app-mysql
    restart: on-failure
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    environment:
      - MYSQL_USER=app
      - MYSQL_ROOT_PASSWORD=app@mysql
      - MYSQL_PASSWORD=app@mysql
      - MYSQL_DATABASE=expanseapp